### ISSUE TITLE
Buffer-local point-stack

### ISSUE THREAD

**Issue by agreselin** [dgutov/point-stack#4]
Hello, is it possible to set up a buffer-local point stack, so that navigating it never changes the window's buffer?

**Comment by dgutov** [comment]
That... sounds like mark rings. Which is the half-baked abstraction that never made sense to me.

So I'm not sure how it would be used. But you can add an override advice to `point-stack--value`.

Anyway, you might want to check out https://github.com/boyw165/history/, which has more of a UI than this package.

**Comment by agreselin** [comment]
> That... sounds like mark rings.

Except that your package allows me to navigate forward and to forget to `C-SPC C-SPC` before `C-U C-SPC`.

> you can add an override advice to point-stack--value

The working of the package is quite beyond my understanding, I was ready to `make-variable-buffer-local` a list of positions, but it is a bit more complex than that. Can you help me out with the advice please?

**Comment by dgutov** [comment]
You basically write a new implementation for `point-stack--value` that uses a buffer-local variable. And then apply it to `:override` the existing function using the `nadvice` package.

See the `advice-add` example here: https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html

**Comment by agreselin** [comment]
What do you say?
```
(defvar-local point-stack-history nil
  "History of point positions in the current buffer.")

(define-advice point-stack--value (:override (name action &optional arg) point-stack-buffer-local)
  "Make the point stack buffer-local."
  (let* ((parameter (intern (concat "point-stack-" (symbol-name name))))
         (value (alist-get parameter point-stack-history))) ; <--- Changes here...
    (cond ((eq action 'car)
           (car value))
          ((eq action 'null)
           (null value))
          (t (setf (alist-get parameter point-stack-history) ; <-- ...and here.
                                   (pcase action
                                     (`set arg)
                                     (`push (cons arg value))
                                     (`shift (cdr value))))))))
```

**Comment by dgutov** [comment]
`define-advice` is the old way of writing advices, I recommend not doing that.

Otherwise, the code looks... possible correct? You can edebug it, if it doesn't behave as you expect it.

**Comment by dgutov** [comment]
Um, actually, scratch that. `define-advice` is okay, I just never seen this macro before. :-)

**Comment by agreselin** [comment]
It's working fine so far. Thank you for the tips :-)

**Comment by dgutov** [comment]
No problem!
